from setuptools import setup, find_packages
import os

setup(
    name="GeoLightning",
    version="0.1.0",
    author="Augusto Mathias Adams",
    author_email="augusto.adams@ufpr.br",
    description="Sistema de geolocalização de descargas atmosféricas utilizando algoritmos genéticos",
    long_description=open("README.md").read(
    ) if os.path.exists("README.md") else "",
    long_description_content_type="text/markdown",
    url="https://github.com/superflankerCTBA/geolightning",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    python_requires=">=3.8",
    install_requires=[
        "certifi>=2025.4.26",
        "charset-normalizer>=3.4.2",
        "contourpy>=1.3.2",
        "coverage>=7.8.1",
        "cycler>=0.12.1",
        "exceptiongroup>=1.3.0",
        "fonttools>=4.58.0",
        "idna>=3.10",
        "iniconfig>=2.1.0",
        "kiwisolver>=1.4.8",
        "llvmlite>=0.44.0",
        "matplotlib>=3.10.3",
        "mealpy>=3.0.1",
        "numba>=0.61.2",
        "numpy>=2.2.6",
        "opfunu>=1.0.4",
        "packaging>=25.0",
        "pandas>=2.2.3",
        "pillow>=11.2.1",
        "pluggy>=1.6.0",
        "pyparsing>=3.2.3",
        "pytest>=8.3.5",
        "pytest-cov>=6.1.1",
        "python-dateutil>=2.9.0.post0",
        "pytz>=2025.2",
        "requests>=2.32.3",
        "scipy>=1.15.3",
        "six>=1.17.0",
        "tomli>=2.2.1",
        "typing_extensions>=4.13.2",
        "tzdata>=2025.2",
        "urllib3>=2.4.0"
    ],
)
